### ISSUE TITLE
Rename to Basis-Universal-Transcoders?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/Basis-Universal-Transcoders#17]
Per discussion last week, is it OK if I rename this repository `Basis-Universal-Transcoders`? GitHub will automatically redirect from the old URL.

/cc @lexaknyazev @bghgary

**Comment by bghgary** [comment]
I was there for the discussions last week, but that seems fine to me.

**Comment by lexaknyazev** [comment]
Sure. Afterwards, we should also update readme and `package*.json` files.

**Comment by donmccurdy** [comment]
OK — repository has been renamed, and remaining changes applied in https://github.com/KhronosGroup/Basis-Universal-Transcoders/pull/18.
